services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: alcaldia_db
      POSTGRES_USER: alcaldia_app
      POSTGRES_PASSWORD: alcaldia_pass_local
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alcaldia_app -d alcaldia_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
